# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='widget',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
