# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_problem_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('JV', 'Java'), ('PY', 'Python'), ('CP', 'C++')], default='JA', max_length=2),
            preserve_default=False,
        ),
    ]
