# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_problem_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runsubmission',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='type',
        ),
        migrations.DeleteModel(
            name='RunSubmission',
        ),
    ]
