# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_auto_20170125_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
