# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_auto_20170126_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='compiled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
