# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_auto_20170128_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='competition.Division'),
        ),
    ]
